name: Release

on:
  release:
    types: [published]

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore src/Reviewabot
      
    - name: Build
      run: dotnet build src/Reviewabot --no-restore -c Release  -f net8.0
      
    - name: Test
      run: dotnet test src/Reviewabot --no-build --verbosity normal

    - name: Publish linux-x64
      run: dotnet publish src/Reviewabot/Reviewabot.Console -r linux-x64 -p:PublishSingleFile=true --self-contained false -c Release -f net8.0

    - name: Rename
      run: mv //home/runner/work/reviewabot/reviewabot/src/Reviewabot/Reviewabot.Console/bin/Release/net8.0/linux-x64/publish/Reviewabot.Console Reviewabot.Console-linux-x64

    - name: Upload Release Asset  
      uses: AButler/upload-release-assets@v3.0
      with:
        files: "Reviewabot.Console-linux-x64"
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        release-tag: ${{github.event.release.tag_name}}
